"""
AI智能体 Schemas 模块
"""

from .ai_agent import (
    AIAgentBase,
    AIAgentCreate,
    AIAgentUpdate,
    AIAgentInDB,
    AIAgentResponse,
    AIAgentListResponse,
    AgentTestRequest,
    AgentChatRequest,
    AgentTestResponse,
    AgentStatisticsData,
    AgentUsageCreate,
    AgentUsageResponse,
    AgentUsageListResponse,
    AgentUsageStatistics,
    ConversationSummary,
    ConversationMessage,
    HotQuestionBucket,
    StudentChainSession,
    ConversationExportRequest,
)

from .model_discovery import (
    AIServiceProvider,
    AIModelInfo,
    ServiceProviderConfig,
    ModelDiscoveryRequest,
    ModelDiscoveryResponse,
    ProviderDetectionResult,
    COMMON_MODEL_PRESETS,
)

from .group_discussion import (
    GroupDiscussionJoinRequest,
    GroupDiscussionJoinResponse,
    GroupDiscussionMessageOut,
    GroupDiscussionMessageListResponse,
    GroupDiscussionSendRequest,
    GroupDiscussionGroupOut,
    GroupDiscussionGroupListResponse,
    GroupDiscussionPublicConfig,
    GroupDiscussionAdminSessionOut,
    GroupDiscussionAdminSessionListResponse,
    GroupDiscussionAdminMessageListResponse,
    GroupDiscussionAdminAnalyzeRequest,
    GroupDiscussionAdminAnalyzeResponse,
    GroupDiscussionAdminCompareAnalyzeRequest,
    GroupDiscussionAdminAnalysisOut,
    GroupDiscussionAdminAnalysisListResponse,
)

__all__ = [
    "AIAgentBase",
    "AIAgentCreate", 
    "AIAgentUpdate",
    "AIAgentInDB",
    "AIAgentResponse",
    "AIAgentListResponse",
    "AgentTestRequest",
    "AgentChatRequest",
    "AgentTestResponse",
    "AgentStatisticsData",
    "AgentUsageCreate",
    "AgentUsageResponse",
    "AgentUsageListResponse",
    "AgentUsageStatistics",
    "ConversationSummary",
    "ConversationMessage",
    "HotQuestionBucket",
    "StudentChainSession",
    "ConversationExportRequest",
    # 模型发现相关
    "AIServiceProvider",
    "AIModelInfo",
    "ServiceProviderConfig",
    "ModelDiscoveryRequest",
    "ModelDiscoveryResponse",
    "ProviderDetectionResult",
    "COMMON_MODEL_PRESETS",
    "GroupDiscussionJoinRequest",
    "GroupDiscussionJoinResponse",
    "GroupDiscussionMessageOut",
    "GroupDiscussionMessageListResponse",
    "GroupDiscussionSendRequest",
    "GroupDiscussionGroupOut",
    "GroupDiscussionGroupListResponse",
    "GroupDiscussionPublicConfig",
    "GroupDiscussionAdminSessionOut",
    "GroupDiscussionAdminSessionListResponse",
    "GroupDiscussionAdminMessageListResponse",
    "GroupDiscussionAdminAnalyzeRequest",
    "GroupDiscussionAdminAnalyzeResponse",
    "GroupDiscussionAdminCompareAnalyzeRequest",
    "GroupDiscussionAdminAnalysisOut",
    "GroupDiscussionAdminAnalysisListResponse",
]
