/** 机器学习学习资源。 */
import type { ResourceItem } from "./data";

export const RESOURCE_TYPE_CONFIG: Record<string, { label: string; color: string }> = {
  book: { label: "书籍", color: "var(--ws-color-primary)" },
  course: { label: "课程", color: "var(--ws-color-success)" },
  github: { label: "GitHub", color: "var(--ws-color-purple)" },
  competition: { label: "竞赛", color: "var(--ws-color-warning)" },
  video: { label: "视频", color: "var(--ws-color-danger)" },
  paper: { label: "论文", color: "var(--ws-color-info)" },
  blog: { label: "博客", color: "var(--ws-color-secondary)" },
};

export const RESOURCES_DATA: ResourceItem[] = [
  // ── 书籍 ──
  {
    title: "机器学习（西瓜书）",
    type: "book",
    description: "周志华著，国内最经典的机器学习入门教材，理论体系完整，涵盖监督学习、集成学习、聚类等核心主题。",
    url: "https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/MLbook2016.htm",
    rating: 5,
    author: "周志华",
    language: "zh",
  },
  {
    title: "统计学习方法（第2版）",
    type: "book",
    description: "李航著，对 SVM、EM、HMM、CRF 等经典算法的数学推导极为细致，是国内 ML 面试必读书目。",
    url: "https://github.com/fengdu78/lihang-code",
    rating: 5,
    author: "李航",
    language: "zh",
  },
  {
    title: "Deep Learning（花书）",
    type: "book",
    description: "Goodfellow、Bengio、Courville 合著，深度学习领域公认的圣经级教科书，覆盖理论与实践深度。",
    url: "https://www.deeplearningbook.org",
    rating: 5,
    author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
    language: "en",
  },
  {
    title: "动手学深度学习 (D2L)",
    type: "book",
    description: "李沐等著，开创性将理论讲解与可运行代码结合，提供 PyTorch/MXNet/JAX 三版本实现，含配套中文视频。",
    url: "https://d2l.ai",
    rating: 5,
    author: "Aston Zhang, Zachary C. Lipton, 李沐, Alex J. Smola",
    language: "zh",
  },
  {
    title: "Pattern Recognition and Machine Learning (PRML)",
    type: "book",
    description: "Bishop 著，贝叶斯视角的经典 ML 教材，数学推导严谨，适合有基础后深入理解 ML 原理。",
    url: "https://www.microsoft.com/en-us/research/people/cmbishop/prml-book/",
    rating: 5,
    author: "Christopher M. Bishop",
    language: "en",
  },
  {
    title: "An Introduction to Statistical Learning (ISLR)",
    type: "book",
    description: "James、Witten 等著，轻量级统计学习入门书，配合 R/Python 实验，比 ESL 更易上手。",
    url: "https://www.statlearning.com",
    rating: 4,
    author: "Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani",
    language: "en",
  },
  {
    title: "The Elements of Statistical Learning (ESL)",
    type: "book",
    description: "Hastie、Tibshirani、Friedman 合著，统计学习理论的「圣经」，数学深度最高，适合研究者精读。",
    url: "https://hastie.su.domains/ElemStatLearn/",
    rating: 5,
    author: "Trevor Hastie, Robert Tibshirani, Jerome Friedman",
    language: "en",
  },
  {
    title: "Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow",
    type: "book",
    description: "Aurélien Géron 著，实战导向的 ML 入门书，每一章都有完整可运行的代码案例和项目。",
    url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125974/",
    rating: 4,
    author: "Aurélien Géron",
    language: "en",
  },

  // ── 课程 ──
  {
    title: "Andrew Ng Machine Learning Specialization",
    type: "course",
    description: "Coursera 上最知名的 ML 入门课，从线性回归到神经网络，零基础友好，有中文翻译和编程作业。",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    rating: 5,
    author: "Andrew Ng (Stanford / DeepLearning.AI)",
    language: "en",
  },
  {
    title: "李宏毅机器学习",
    type: "course",
    description: "台湾大学公开课，讲解深入浅出，大量动画图示和幽默比喻，覆盖从 ML 基础到 LLM 的最新技术。",
    url: "https://speech.ee.ntu.edu.tw/~hylee/ml/2023-spring.php",
    rating: 5,
    author: "李宏毅 (台湾大学)",
    language: "zh",
  },
  {
    title: "Stanford CS229: Machine Learning",
    type: "course",
    description: "Stanford 经典 ML 研究生课，数学推导最完整的公开课，适合追求理论深度的学习者。",
    url: "https://cs229.stanford.edu",
    rating: 4,
    author: "Andrew Ng (Stanford)",
    language: "en",
  },
  {
    title: "Stanford CS231n: CNNs for Visual Recognition",
    type: "course",
    description: "计算机视觉方向最经典的课程，系统讲解 CNN、RNN、GAN、Transformer 在视觉中的应用。",
    url: "http://cs231n.stanford.edu",
    rating: 5,
    author: "Fei-Fei Li (Stanford)",
    language: "en",
  },
  {
    title: "Stanford CS224n: NLP with Deep Learning",
    type: "course",
    description: "NLP 方向最权威的课程，从词向量到 Transformer 到大模型，紧跟学术前沿。",
    url: "https://web.stanford.edu/class/cs224n/",
    rating: 5,
    author: "Christopher Manning (Stanford)",
    language: "en",
  },
  {
    title: "MIT 6.S191: Introduction to Deep Learning",
    type: "course",
    description: "MIT 官方深度学习入门课，每年更新，软件实验用 TensorFlow/PyTorch，含最新研究 guest lecture。",
    url: "http://introtodeeplearning.com",
    rating: 4,
    author: "Alexander Amini, Ava Soleimany (MIT)",
    language: "en",
  },
  {
    title: "Fast.ai Practical Deep Learning",
    type: "course",
    description: "自顶向下的教学方式，先写代码跑出结果再学原理，极大降低深度学习入门门槛。",
    url: "https://course.fast.ai",
    rating: 4,
    author: "Jeremy Howard (Fast.ai)",
    language: "en",
  },
  {
    title: "Full Stack Deep Learning",
    type: "course",
    description: "专注深度学习产品化全流程，从数据管理、训练、部署到监控，覆盖 MLOps 核心技术栈。",
    url: "https://fullstackdeeplearning.com",
    rating: 4,
    author: "UC Berkeley / The Full Stack Team",
    language: "en",
  },

  // ── GitHub 仓库 ──
  {
    title: "microsoft/ML-For-Beginners",
    type: "github",
    description: "微软出品的 12 周 ML 入门课程，含完整教案、Notebook、测验和项目，26 种语言版本。",
    url: "https://github.com/microsoft/ML-For-Beginners",
    rating: 5,
    author: "Microsoft",
    language: "zh",
  },
  {
    title: "d2l-ai/d2l-zh",
    type: "github",
    description: "《动手学深度学习》中文版官方仓库，每个章节都是可交互的 Jupyter Notebook。",
    url: "https://github.com/d2l-ai/d2l-zh",
    rating: 5,
    author: "D2L 社区",
    language: "zh",
  },
  {
    title: "scikit-learn/scikit-learn",
    type: "github",
    description: "scikit-learn 官方仓库，文档极好，源码清晰，学习经典 ML 算法实现的最佳阅读材料。",
    url: "https://github.com/scikit-learn/scikit-learn",
    rating: 5,
    author: "scikit-learn 社区",
    language: "en",
  },
  {
    title: "huggingface/transformers",
    type: "github",
    description: "Hugging Face Transformers 核心库，支持 1000+ 预训练模型和 20+ 架构，GitHub 上最活跃的 ML 项目之一。",
    url: "https://github.com/huggingface/transformers",
    rating: 5,
    author: "Hugging Face",
    language: "en",
  },
  {
    title: "mlabonne/llm-course",
    type: "github",
    description: "从零开始的 LLM 学习路线图，覆盖数学基础、架构、预训练、微调、RLHF 全链路。",
    url: "https://github.com/mlabonne/llm-course",
    rating: 5,
    author: "Maxime Labonne",
    language: "en",
  },
  {
    title: "rasbt/LLMs-from-scratch",
    type: "github",
    description: "Sebastian Raschka 的「从零构建大型语言模型」配套代码，逐行实现 GPT 类模型，配有完整书本。",
    url: "https://github.com/rasbt/LLMs-from-scratch",
    rating: 4,
    author: "Sebastian Raschka",
    language: "en",
  },
  {
    title: "practical-tutorials/project-based-learning",
    type: "github",
    description: "超全的项目驱动学习教程汇总，覆盖 Python/ML/DL/NLP 等方向，适合练手构建作品集。",
    url: "https://github.com/practical-tutorials/project-based-learning",
    rating: 4,
    author: "practical-tutorials 社区",
    language: "en",
  },
  {
    title: "eugeneyan/applied-ml",
    type: "github",
    description: "精选的工业界 ML 应用论文和技术博客汇总，按推荐系统、NLP、CV 等方向分类整理。",
    url: "https://github.com/eugeneyan/applied-ml",
    rating: 4,
    author: "Eugene Yan",
    language: "en",
  },

  // ── 数据竞赛 ──
  {
    title: "Kaggle",
    type: "competition",
    description: "全球最大的数据科学竞赛平台，拥有海量数据集、Notebook 环境和活跃社区，ML 练手必选。",
    url: "https://www.kaggle.com",
    rating: 5,
    author: "Google",
    language: "en",
  },
  {
    title: "天池 (Tianchi)",
    type: "competition",
    description: "阿里巴巴主办的数据竞赛平台，赛题来自真实业务场景，奖金丰厚，提供免费 GPU 算力。",
    url: "https://tianchi.aliyun.com",
    rating: 4,
    author: "阿里巴巴",
    language: "zh",
  },
  {
    title: "和鲸社区 (Heywhale)",
    type: "competition",
    description: "国内最大的数据科学社区之一，集竞赛、课程、数据集、Notebook 云端环境于一体。",
    url: "https://www.heywhale.com",
    rating: 4,
    author: "和鲸科技",
    language: "zh",
  },
  {
    title: "DrivenData",
    type: "competition",
    description: "聚焦社会公益的数据科学竞赛平台，用 ML 解决公共卫生、环保、扶贫等真实社会问题。",
    url: "https://www.drivendata.org",
    rating: 4,
    author: "DrivenData",
    language: "en",
  },

  // ── 视频 ──
  {
    title: "3Blue1Brown 神经网络系列",
    type: "video",
    description: "精美数学动画讲解神经网络、反向传播、梯度下降等核心概念，直观理解大于公式推导。",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
    rating: 5,
    author: "3Blue1Brown (Grant Sanderson)",
    language: "en",
  },
  {
    title: "StatQuest 机器学习系列",
    type: "video",
    description: "用最通俗的方式讲解每个 ML 算法原理，配有手绘动画和逐步推导，零数学基础也能看懂。",
    url: "https://www.youtube.com/@statquest",
    rating: 5,
    author: "Josh Starmer (StatQuest)",
    language: "en",
  },
  {
    title: "李沐动手学深度学习 B 站系列",
    type: "video",
    description: "李沐本人在 B 站录制的完整 D2L 教学视频，论文精读 + 代码逐行讲解，极为精准。",
    url: "https://space.bilibili.com/1567748478/channel/seriesdetail?sid=358497",
    rating: 5,
    author: "李沐 (Amazon/AWS)",
    language: "zh",
  },
  {
    title: "Two Minute Papers",
    type: "video",
    description: "用 2-5 分钟短视频介绍最新 AI 论文精华，画面精美、讲解生动，适合快速了解前沿动态。",
    url: "https://www.youtube.com/@TwoMinutePapers",
    rating: 4,
    author: "Károly Zsolnai-Fehér",
    language: "en",
  },
  {
    title: "Andrej Karpathy YouTube 频道",
    type: "video",
    description: "OpenAI 联合创始人的教学频道，手写 GPT、微调技巧、makemore 系列 Tutorial，极其硬核。",
    url: "https://www.youtube.com/@AndrejKarpathy",
    rating: 5,
    author: "Andrej Karpathy",
    language: "en",
  },

  // ── 论文 ──
  {
    title: "Attention Is All You Need (Transformer)",
    type: "paper",
    description: "2017 年 Google 团队提出的 Transformer 架构论文，彻底改变了 NLP 并催生 GPT/BERT/LLM 时代。",
    url: "https://arxiv.org/abs/1706.03762",
    rating: 5,
    author: "Vaswani et al. (Google)",
    language: "en",
  },
  {
    title: "Deep Residual Learning for Image Recognition (ResNet)",
    type: "paper",
    description: "何恺明 2016 年提出残差网络，解决了深层网络退化问题，被引量超 20 万次，CV 里程碑。",
    url: "https://arxiv.org/abs/1512.03385",
    rating: 5,
    author: "Kaiming He et al. (Microsoft Research)",
    language: "en",
  },
  {
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    type: "paper",
    description: "Google 2018 年提出的预训练语言模型，开创 NLP 预训练-微调范式，至今仍广泛使用。",
    url: "https://arxiv.org/abs/1810.04805",
    rating: 5,
    author: "Devlin et al. (Google)",
    language: "en",
  },
  {
    title: "Generative Adversarial Nets (GAN)",
    type: "paper",
    description: "Goodfellow 2014 年提出生成对抗网络，开创性地用博弈论思想实现高质量生成模型。",
    url: "https://arxiv.org/abs/1406.2661",
    rating: 5,
    author: "Ian Goodfellow et al.",
    language: "en",
  },
  {
    title: "XGBoost: A Scalable Tree Boosting System",
    type: "paper",
    description: "陈天奇 2016 年论文，系统介绍 XGBoost 设计原理和优化技术，Kaggle 竞赛称霸的基石。",
    url: "https://arxiv.org/abs/1603.02754",
    rating: 4,
    author: "Tianqi Chen, Carlos Guestrin (UW)",
    language: "en",
  },

  // ── 博客 ──
  {
    title: "The Illustrated Transformer",
    type: "blog",
    description: "Jay Alammar 用精美插图逐层拆解 Transformer、BERT、GPT 架构，图文并茂，ML 博客经典之作。",
    url: "https://jalammar.github.io/illustrated-transformer/",
    rating: 5,
    author: "Jay Alammar",
    language: "en",
  },
  {
    title: "Lil'Log (Lilian Weng)",
    type: "blog",
    description: "OpenAI 安全系统负责人 Lilian Weng 的技术长文博客，深入讲解 RLHF、Agent、扩散模型等前沿主题。",
    url: "https://lilianweng.github.io",
    rating: 5,
    author: "Lilian Weng",
    language: "en",
  },
  {
    title: "Distill.pub",
    type: "blog",
    description: "专注于 ML 可解释性和可视化的期刊式博客，每篇文章都经过严格同行评审，交互式可视化堪称艺术品。",
    url: "https://distill.pub",
    rating: 4,
    author: "Distill 社区",
    language: "en",
  },
];
