/** 机器学习学习路线 - 真实学习路径 */
import type { RoadmapStage } from "./data";

export const ROADMAP_STAGES: RoadmapStage[] = [
  {
    id: "basics",
    name: "入门基础",
    duration: "4-6 周",
    color: "var(--ws-color-primary)",
    topics: [
      "线性代数基础：矩阵运算、特征值与特征向量、SVD 分解",
      "概率论与统计：条件概率、贝叶斯定理、正态分布、最大似然估计",
      "微积分核心：偏导数、梯度、链式法则、拉格朗日乘子法",
      "Python 科学计算栈：NumPy 向量化运算、广播机制、linalg 模块",
      "Pandas 数据处理：DataFrame 操作、groupby、merge、时间序列处理",
      "Matplotlib / Seaborn 可视化：折线图、散点图、直方图、热力图、子图布局",
      "Scikit-learn 初步：train_test_split、fit/predict/transform 统一 API",
      "机器学习基本概念：监督学习 vs 无监督学习 vs 半监督学习",
      "偏差与方差权衡、过拟合与欠拟合诊断",
      "交叉验证原理：K-Fold、StratifiedKFold 与 Leave-One-Out",
    ],
    milestones: [
      "用 NumPy 从零实现一个线性回归（梯度下降）",
      "完成 Titanic 生存预测 Kaggle 入门竞赛并提交预测",
      "用 Pandas + Seaborn 完成一份探索性数据分析报告（EDA）",
      "能够解释过拟合/欠拟合，并画出学习曲线",
    ],
    status: "pending",
  },
  {
    id: "core-algorithms",
    name: "核心算法",
    duration: "8-12 周",
    color: "var(--ws-color-success)",
    topics: [
      "线性回归：正规方程、梯度下降变体（SGD/MBGD）、正则化（L1 Lasso / L2 Ridge / ElasticNet）",
      "逻辑回归：Sigmoid 函数、决策边界、多分类（OvR/Softmax）、对数损失",
      "决策树：ID3/C4.5/CART、信息增益与基尼系数、剪枝策略",
      "集成学习 Bagging：随机森林原理、OOB 误差估计、特征重要性",
      "集成学习 Boosting：AdaBoost、Gradient Boosting、XGBoost、LightGBM、CatBoost",
      "支持向量机 (SVM)：最大间隔分类、核函数（线性/多项式/RBF）、软间隔与 C 参数",
      "朴素贝叶斯：高斯/多项式/伯努利变体、拉普拉斯平滑",
      "K 近邻 (KNN)：距离度量（欧氏/曼哈顿/余弦）、KD-Tree 加速、维度灾难",
      "聚类算法：K-Means/DBSCAN/Hierarchical Clustering、轮廓系数评估",
      "降维技术：PCA 主成分分析、t-SNE 可视化、UMAP",
      "特征工程：缺失值处理、编码（One-Hot/Ordinal/Target）、分箱、特征交叉、特征选择（Filter/Wrapper/Embedded）",
      "模型评估：混淆矩阵、Precision/Recall/F1、ROC-AUC、对数损失、回归指标（MSE/MAE/R²）",
    ],
    milestones: [
      "在 Kaggle House Prices 竞赛中使用 XGBoost 进入 Top 30%",
      "独立完成从数据清洗到模型评估的完整 Pipeline（用 Scikit-learn Pipeline）",
      "用 GridSearchCV/RandomizedSearchCV 完成一次超参数调优",
      "使用 PCA + t-SNE 对高维数据进行降维可视化",
      "撰写一篇对比 5 种分类算法在同一数据集上性能的技术博客",
    ],
    status: "pending",
  },
  {
    id: "deep-learning",
    name: "深度学习",
    duration: "10-14 周",
    color: "var(--ws-color-info)",
    topics: [
      "神经网络基础：感知机、多层感知机 (MLP)、激活函数（ReLU/GELU/Swish）、反向传播推导",
      "PyTorch 核心：Tensor/autograd/nn.Module/Dataset & DataLoader/GPU 训练",
      "卷积神经网络 (CNN)：卷积层、池化层、感受野、经典架构（LeNet/AlexNet/VGG/ResNet）",
      "迁移学习：预训练权重加载、特征提取与微调、ImageNet 预训练模型",
      "循环神经网络 (RNN/LSTM/GRU)：序列建模、BPTT、双向 RNN、注意力机制",
      "Transformer 架构：Self-Attention/Multi-Head Attention/Positional Encoding/LayerNorm",
      "Batch Normalization / Layer Normalization / Dropout / Label Smoothing",
      "优化器对比：SGD+Momentum/Adam/AdamW/RMSprop、学习率调度（Cosine Annealing/Warmup/ReduceLROnPlateau）",
      "损失函数深度：交叉熵/Focal Loss/对比损失（Triplet/Contrastive）/ CTC Loss",
      "数据增强：图像增强（RandomCrop/ColorJitter/MixUp/CutMix）、文本增强（回译/EDA）",
      "分布式训练基础：DataParallel vs DistributedDataParallel、混合精度训练（FP16/BF16）",
      "正则化与泛化：Weight Decay/Early Stopping/Gradient Clipping/Stochastic Depth",
    ],
    milestones: [
      "用 PyTorch 从零实现一个 MLP 并在 MNIST 上达到 98%+ 准确率",
      "微调 ResNet-50 在 CIFAR-10 上达到 90%+ 准确率",
      "用 LSTM 实现一个字符级文本生成器",
      "实现一个微型 Transformer 用于序列到序列任务（如日期格式转换）",
      "在 Kaggle 图像分类竞赛中完成一次完整提交并撰写实验报告",
    ],
    status: "pending",
  },
  {
    id: "advanced",
    name: "进阶专题",
    duration: "8-12 周",
    color: "var(--ws-color-warning)",
    topics: [
      "自然语言处理 (NLP)：分词/词向量（Word2Vec/GloVe）、文本分类、命名实体识别 (NER)、序列标注",
      "预训练语言模型：BERT/GPT 架构、Masked LM vs Autoregressive LM、tokenizer（BPE/WordPiece）",
      "HuggingFace Transformers 实战：AutoModel/AutoTokenizer、Trainer API、PEFT",
      "计算机视觉进阶：目标检测（YOLO/Faster R-CNN）、语义分割（UNet/DeepLab）、实例分割（Mask R-CNN）",
      "生成模型：GAN（DCGAN/WGAN）、VAE 变分自编码器、扩散模型原理（DDPM/Stable Diffusion）",
      "推荐系统：协同过滤（UserCF/ItemCF）、矩阵分解（SVD++/ALS）、FM/DeepFM/NCF",
      "强化学习：MDP 马尔可夫决策过程、Q-Learning/SARSA、DQN/PPO、OpenAI Gym 环境",
      "图神经网络 (GNN)：GCN/GAT/GraphSAGE、消息传递框架、DGL/PyG 框架",
      "时序预测：ARIMA/Prophet/Informer、时序 Transformer、异常检测",
      "自监督学习：SimCLR/MoCo/MAE、对比学习原理",
    ],
    milestones: [
      "用 HuggingFace BERT 微调一个中文情感分类模型，准确率 >90%",
      "训练 YOLOv8 在自己标注的数据集上完成目标检测",
      "实现一个基于协同过滤的电影推荐系统",
      "用 DQN 训练一个 Atari 游戏智能体（如 CartPole 或 Pong）",
      "阅读并复现一篇顶会论文的核心方法（如 SimCLR 或 BERT）",
    ],
    status: "pending",
  },
  {
    id: "production",
    name: "工程实践",
    duration: "6-10 周",
    color: "var(--ws-color-purple)",
    topics: [
      "FastAPI 模型服务：pydantic Schema/异步端点/后台任务",
      "Docker 容器化：Dockerfile/多阶段构建/Docker Compose/GPU 驱动配置",
      "模型实验管理 MLflow：参数追踪/指标记录/模型注册/模型版本对比",
      "MLOps 流水线：数据版本控制（DVC）/模型 CI/CD/ Feature Store 概念",
      "模型监控与可观测性：数据漂移检测/模型性能退化告警/Prometheus + Grafana",
      "模型加速：ONNX 格式导出/量化（INT8/INT4）、TensorRT 推理优化",
      "模型剪枝与知识蒸馏：结构化剪枝/DistilBERT 风格蒸馏",
      "A/B 测试：实验设计/样本量计算/统计显著性检验（t-test/chi-square）",
      "云端部署：模型打包为 REST API + Docker 镜像部署到 AWS/GCP/阿里云",
      "项目展示：GitHub 作品集、技术博客、Kaggle Master 冲击",
    ],
    milestones: [
      "部署一个 FastAPI 模型推理服务并用 Docker 打包（含测试与文档）",
      "使用 MLflow 追踪至少 10 次模型实验并对比最佳结果",
      "将一个 PyTorch 模型量化为 INT8 并部署为 ONNX 格式",
      "设计并执行一次完整的 A/B 测试实验并撰写分析报告",
      "发布至少 2 个完整项目的 GitHub 仓库（含 README/Notebook/requirements）",
    ],
    status: "pending",
  },
];
