/** 机器学习工具集。 */
import type { ToolItem } from "./data";

export const CATEGORY_LABELS: Record<string, string> = {
  "dev-env": "开发环境",
  "data-processing": "数据处理",
  "data-viz": "数据可视化",
  "ml-lib": "经典 ML 库",
  "dl-framework": "深度学习框架",
  "llm-ecosystem": "大模型生态",
  "vector-db": "向量数据库",
  mlops: "MLOps",
};

export const DIFFICULTY_LABELS: Record<string, { label: string; variant: string }> = {
  beginner: { label: "入门", variant: "success" },
  intermediate: { label: "中级", variant: "warning" },
  advanced: { label: "高级", variant: "danger" },
};

export const TOOLS_DATA: ToolItem[] = [
  // ── 开发环境 ──
  {
    name: "Jupyter Notebook",
    description: "交互式编程环境，支持代码、文本、图表混合编写，是数据科学和 ML 实验的标配工具。",
    category: "dev-env",
    url: "https://jupyter.org",
    gettingStarted: "https://jupyter.org/try",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "VS Code",
    description: "微软出品的轻量级编辑器，结合 Python、Jupyter、GitHub Copilot 等插件可构建高效的 ML 开发环境。",
    category: "dev-env",
    url: "https://code.visualstudio.com",
    gettingStarted: "https://code.visualstudio.com/docs/datascience/overview",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Google Colab",
    description: "Google 提供的免费云端 Jupyter 环境，内置 GPU/TPU、预装主流 ML 库，适合快速实验和学习。",
    category: "dev-env",
    url: "https://colab.research.google.com",
    gettingStarted: "https://colab.research.google.com/notebooks/intro.ipynb",
    difficulty: "beginner",
    pricing: "免费+付费",
  },
  {
    name: "JupyterLab",
    description: "Jupyter 的下一代界面，支持多标签、文件浏览器、终端等高级工作区，适合复杂项目。",
    category: "dev-env",
    url: "https://jupyterlab.readthedocs.io",
    gettingStarted: "https://jupyterlab.readthedocs.io/en/stable/getting_started/overview.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Kaggle Notebooks",
    description: "Kaggle 平台内嵌的云端 Notebook，免费 GPU、海量内置数据集，可直接参与竞赛。",
    category: "dev-env",
    url: "https://www.kaggle.com/code",
    gettingStarted: "https://www.kaggle.com/docs/notebooks",
    difficulty: "beginner",
    pricing: "免费+付费",
  },
  {
    name: "Deepnote",
    description: "团队协作型数据科学 Notebook，支持实时协作、SQL、环境变量管理，适合团队项目。",
    category: "dev-env",
    url: "https://deepnote.com",
    gettingStarted: "https://deepnote.com/docs",
    difficulty: "beginner",
    pricing: "免费+付费",
  },

  // ── 数据处理 ──
  {
    name: "Pandas",
    description: "Python 数据分析核心库，提供高性能 DataFrame 结构和丰富的数据清洗、转换、聚合功能。",
    category: "data-processing",
    url: "https://pandas.pydata.org",
    gettingStarted: "https://pandas.pydata.org/docs/getting_started/index.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "NumPy",
    description: "Python 科学计算基础库，提供多维数组对象和广播、线性代数、傅里叶变换等高效运算。",
    category: "data-processing",
    url: "https://numpy.org",
    gettingStarted: "https://numpy.org/doc/stable/user/quickstart.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Polars",
    description: "用 Rust 编写的高性能 DataFrame 库，惰性求值和表达式 API，比 Pandas 更快的替代方案。",
    category: "data-processing",
    url: "https://pola.rs",
    gettingStarted: "https://docs.pola.rs/user-guide/getting-started/",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "DuckDB",
    description: "嵌入式 OLAP 数据库引擎，支持直接查询 Parquet/CSV/JSON 文件，无需数据导入。",
    category: "data-processing",
    url: "https://duckdb.org",
    gettingStarted: "https://duckdb.org/docs/",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Dask",
    description: "并行计算框架，兼容 Pandas/NumPy API，能处理超出内存容量的大规模数据集。",
    category: "data-processing",
    url: "https://dask.org",
    gettingStarted: "https://docs.dask.org/en/stable/10-minutes-to-dask.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Apache Arrow",
    description: "跨语言的列式内存格式，实现不同系统间零拷贝数据交换，是 PySpark/Polars 的基础组件。",
    category: "data-processing",
    url: "https://arrow.apache.org",
    gettingStarted: "https://arrow.apache.org/docs/python/getstarted.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },

  // ── 数据可视化 ──
  {
    name: "Matplotlib",
    description: "Python 最基础的可视化库，可精细控制图表每个元素，是其他高级库的底层依赖。",
    category: "data-viz",
    url: "https://matplotlib.org",
    gettingStarted: "https://matplotlib.org/stable/users/explain/quick_start.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Seaborn",
    description: "基于 Matplotlib 的统计可视化库，内置美观主题和配色，一行代码绘制复杂统计图。",
    category: "data-viz",
    url: "https://seaborn.pydata.org",
    gettingStarted: "https://seaborn.pydata.org/tutorial.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Plotly",
    description: "交互式可视化库，支持缩放、悬停、选择等操作，可导出为独立 HTML 或嵌入 Web 应用。",
    category: "data-viz",
    url: "https://plotly.com",
    gettingStarted: "https://plotly.com/python/getting-started/",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Streamlit",
    description: "纯 Python 构建数据应用的框架，无需前端知识即可快速将 ML 模型包装成交互式 Web 应用。",
    category: "data-viz",
    url: "https://streamlit.io",
    gettingStarted: "https://docs.streamlit.io/get-started",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Gradio",
    description: "快速构建 ML 模型演示界面的库，内置常用组件，一键部署到 Hugging Face Spaces。",
    category: "data-viz",
    url: "https://gradio.app",
    gettingStarted: "https://www.gradio.app/guides/quickstart",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Bokeh",
    description: "面向 Web 浏览器的交互式可视化库，支持大数据集的流式渲染和服务端回调。",
    category: "data-viz",
    url: "https://bokeh.org",
    gettingStarted: "https://docs.bokeh.org/en/latest/docs/first_steps.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },

  // ── 经典 ML 库 ──
  {
    name: "scikit-learn",
    description: "最流行的经典机器学习库，提供分类、回归、聚类、降维等算法的统一 API 和工具链。",
    category: "ml-lib",
    url: "https://scikit-learn.org",
    gettingStarted: "https://scikit-learn.org/stable/getting_started.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "XGBoost",
    description: "梯度提升框架，以极致的速度与精度闻名，Kaggle 竞赛中结构化数据任务的王者。",
    category: "ml-lib",
    url: "https://xgboost.readthedocs.io",
    gettingStarted: "https://xgboost.readthedocs.io/en/stable/get_started.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "LightGBM",
    description: "微软开发的梯度提升框架，基于叶子增长策略，训练速度更快、内存占用更低。",
    category: "ml-lib",
    url: "https://lightgbm.readthedocs.io",
    gettingStarted: "https://lightgbm.readthedocs.io/en/stable/Quick-Start.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "CatBoost",
    description: "Yandex 开发的梯度提升库，原生支持类别特征，无需手动编码，对默认超参数鲁棒。",
    category: "ml-lib",
    url: "https://catboost.ai",
    gettingStarted: "https://catboost.ai/docs/en/concepts/quick-start",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Optuna",
    description: "现代化的超参数优化框架，支持 Pruning、可视化、分布式搜索，远优于 Grid/Random Search。",
    category: "ml-lib",
    url: "https://optuna.org",
    gettingStarted: "https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/001_first.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "SHAP",
    description: "基于博弈论 Shapley 值的模型可解释性工具，可解释任意模型的预测和特征重要性。",
    category: "ml-lib",
    url: "https://shap.readthedocs.io",
    gettingStarted: "https://shap.readthedocs.io/en/latest/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20Shapley%20values.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },

  // ── 深度学习框架 ──
  {
    name: "PyTorch",
    description: "Meta 主导的动态计算图框架，Pythonic 设计、灵活易调试，学术界和工业界首选。",
    category: "dl-framework",
    url: "https://pytorch.org",
    gettingStarted: "https://pytorch.org/tutorials/beginner/basics/intro.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "TensorFlow",
    description: "Google 开发的端到端深度学习平台，Keras 高层 API + TF Serving 生产部署方案成熟。",
    category: "dl-framework",
    url: "https://tensorflow.org",
    gettingStarted: "https://www.tensorflow.org/tutorials",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Keras",
    description: "高等级神经网络 API，以最少的代码快速搭建和训练模型，现已整合为 TensorFlow 官方前端。",
    category: "dl-framework",
    url: "https://keras.io",
    gettingStarted: "https://keras.io/getting_started/",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "JAX",
    description: "Google 开发的高性能数值计算库，支持自动微分、JIT 编译和向量化，前沿研究者常用。",
    category: "dl-framework",
    url: "https://jax.readthedocs.io",
    gettingStarted: "https://jax.readthedocs.io/en/latest/notebooks/quickstart.html",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "FastAI",
    description: "基于 PyTorch 的高层深度学习库，采用自顶向下的教学式 API，10 行代码训练 SOTA 模型。",
    category: "dl-framework",
    url: "https://fast.ai",
    gettingStarted: "https://docs.fast.ai/tutorial.html",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "PaddlePaddle",
    description: "百度开发的深度学习平台，中文文档完善，在工业检测、NLP 预训练等场景有完整产业级套件。",
    category: "dl-framework",
    url: "https://www.paddlepaddle.org.cn",
    gettingStarted: "https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/index_cn.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },

  // ── 大模型生态 ──
  {
    name: "Hugging Face",
    description: "最大的预训练模型社区和库 Hub，Transformers + Datasets + Diffusers 生态完备。",
    category: "llm-ecosystem",
    url: "https://huggingface.co",
    gettingStarted: "https://huggingface.co/learn/nlp-course",
    difficulty: "beginner",
    pricing: "免费+付费",
  },
  {
    name: "LangChain",
    description: "LLM 应用开发框架，提供 Chain、Agent、Memory、Tool 等抽象，生态最丰富的 LLM 编排工具。",
    category: "llm-ecosystem",
    url: "https://www.langchain.com",
    gettingStarted: "https://python.langchain.com/docs/get_started/introduction",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "LlamaIndex",
    description: "专注于数据与 LLM 连接的框架，提供多种索引结构和检索策略，是 RAG 系统的核心工具。",
    category: "llm-ecosystem",
    url: "https://www.llamaindex.ai",
    gettingStarted: "https://docs.llamaindex.ai/en/stable/getting_started/starter_example/",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Ollama",
    description: "一键在本地运行开源 LLM 的工具，支持 LLaMA、Qwen、DeepSeek 等数十种模型，macOS/Linux/Win 均可用。",
    category: "llm-ecosystem",
    url: "https://ollama.com",
    gettingStarted: "https://ollama.com/library",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Dify",
    description: "开源 LLM 应用开发平台，可视化编排 RAG Pipeline、Agent 和 Workflow，适合非开发者使用。",
    category: "llm-ecosystem",
    url: "https://dify.ai",
    gettingStarted: "https://docs.dify.ai",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "LLaMA-Factory",
    description: "集成多种 LLM 微调方法的框架，支持 LoRA/QLoRA/全参微调，Web UI 操作，中文社区使用最为广泛。",
    category: "llm-ecosystem",
    url: "https://github.com/hiyouga/LLaMA-Factory",
    gettingStarted: "https://github.com/hiyouga/LLaMA-Factory?tab=readme-ov-file#quickstart",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "DSPy",
    description: "Stanford 开发的声明式 LLM 编程框架，用编译范式替代手工 Prompt 工程，自动优化模型调用链。",
    category: "llm-ecosystem",
    url: "https://dspy.ai",
    gettingStarted: "https://dspy.ai/tutorials/",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "vLLM",
    description: "高性能 LLM 推理引擎，PagedAttention 技术实现高吞吐推理，是生产环境部署 LLM 的事实标准。",
    category: "llm-ecosystem",
    url: "https://docs.vllm.ai",
    gettingStarted: "https://docs.vllm.ai/en/stable/getting_started/quickstart.html",
    difficulty: "advanced",
    pricing: "开源免费",
  },

  // ── 向量数据库 ──
  {
    name: "Chroma",
    description: "轻量级开源向量数据库，Python 原生集成，零配置启动，是 RAG 原型开发最便捷的选择。",
    category: "vector-db",
    url: "https://www.trychroma.com",
    gettingStarted: "https://docs.trychroma.com/getting-started",
    difficulty: "beginner",
    pricing: "开源免费",
  },
  {
    name: "Qdrant",
    description: "Rust 编写的高性能向量搜索引擎，支持过滤查询、payload 索引和分布式部署。",
    category: "vector-db",
    url: "https://qdrant.tech",
    gettingStarted: "https://qdrant.tech/documentation/quickstart/",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Milvus",
    description: "云原生向量数据库，支持万亿级向量检索，GPU 加速索引，被广泛应用于企业级语义搜索系统。",
    category: "vector-db",
    url: "https://milvus.io",
    gettingStarted: "https://milvus.io/docs/quickstart.md",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "FAISS",
    description: "Meta 开源的向量相似度搜索库，支持十亿级向量索引和 GPU 加速，是许多向量数据库的底层引擎。",
    category: "vector-db",
    url: "https://github.com/facebookresearch/faiss",
    gettingStarted: "https://github.com/facebookresearch/faiss/wiki/Getting-started",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Pinecone",
    description: "全托管向量数据库云服务，免运维、毫秒级延迟，适合快速将 RAG 系统推向生产。",
    category: "vector-db",
    url: "https://www.pinecone.io",
    gettingStarted: "https://docs.pinecone.io/guides/get-started/quickstart",
    difficulty: "beginner",
    pricing: "免费+付费",
  },
  {
    name: "Weaviate",
    description: "支持混合搜索的向量数据库，内置向量化和多模态能力，GraphQL 接口，生态集成丰富。",
    category: "vector-db",
    url: "https://weaviate.io",
    gettingStarted: "https://weaviate.io/developers/weaviate/quickstart",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "pgvector",
    description: "PostgreSQL 向量扩展，无需额外服务即可在现有数据库中启用向量索引和相似度搜索。",
    category: "vector-db",
    url: "https://github.com/pgvector/pgvector",
    gettingStarted: "https://github.com/pgvector/pgvector#setup",
    difficulty: "intermediate",
    pricing: "开源免费",
  },

  // ── MLOps ──
  {
    name: "MLflow",
    description: "Databricks 推出的开源 MLOps 平台，覆盖实验跟踪、模型注册、部署和评估全生命周期。",
    category: "mlops",
    url: "https://mlflow.org",
    gettingStarted: "https://mlflow.org/docs/latest/getting-started/index.html",
    difficulty: "intermediate",
    pricing: "开源免费",
  },
  {
    name: "Weights & Biases",
    description: "业界领先的实验追踪和模型监控平台，自动记录超参数、指标、图表和模型版本。",
    category: "mlops",
    url: "https://wandb.ai",
    gettingStarted: "https://docs.wandb.ai/quickstart",
    difficulty: "intermediate",
    pricing: "免费+付费",
  },
  {
    name: "Docker",
    description: "容器化平台，保证开发、测试、生产环境一致性，是 ML 模型部署的基础设施。",
    category: "mlops",
    url: "https://www.docker.com",
    gettingStarted: "https://docs.docker.com/get-started/",
    difficulty: "intermediate",
    pricing: "免费+付费",
  },
  {
    name: "DVC",
    description: "数据版本控制工具，像管理代码 Git 一样管理数据集和模型文件，支持远程存储后端。",
    category: "mlops",
    url: "https://dvc.org",
    gettingStarted: "https://dvc.org/doc/start",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "BentoML",
    description: "统一的模型打包和部署框架，将任意 ML 模型构建为标准化的 Web 服务 API。",
    category: "mlops",
    url: "https://www.bentoml.com",
    gettingStarted: "https://docs.bentoml.com/en/latest/get-started.html",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "Airflow",
    description: "Apache 工作流调度平台，用 DAG 定义数据/模型流水线，适合复杂的 ML 任务编排场景。",
    category: "mlops",
    url: "https://airflow.apache.org",
    gettingStarted: "https://airflow.apache.org/docs/apache-airflow/stable/start.html",
    difficulty: "advanced",
    pricing: "开源免费",
  },
  {
    name: "Evidently",
    description: "ML 模型监控和漂移检测工具，自动生成数据漂移和模型性能报告，适合生产环境持续监控。",
    category: "mlops",
    url: "https://www.evidentlyai.com",
    gettingStarted: "https://docs.evidentlyai.com/get-started/tutorial",
    difficulty: "advanced",
    pricing: "开源免费",
  },
];
