"""add grade to xbk

Revision ID: 04afffb306ed
Revises: 36b22173a652
Create Date: 2026-02-15 16:06:01.265659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04afffb306ed'
down_revision: Union[str, None] = '36b22173a652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_inf_typst_assets_note_id_path'), table_name='inf_typst_assets')
    op.drop_index(op.f('idx_inf_typst_assets_sha256'), table_name='inf_typst_assets')
    op.drop_index(op.f('idx_inf_typst_categories_sort'), table_name='inf_typst_categories')
    op.drop_index(op.f('idx_inf_typst_notes_compiled_hash'), table_name='inf_typst_notes')
    op.drop_index(op.f('idx_inf_typst_notes_published'), table_name='inf_typst_notes')
    op.drop_index(op.f('idx_inf_typst_styles_sort'), table_name='inf_typst_styles')
    op.add_column('xbk_courses', sa.Column('grade', sa.String(length=20), nullable=True, comment='适用年级（高一/高二）'))
    op.create_index(op.f('ix_xbk_courses_grade'), 'xbk_courses', ['grade'], unique=False)
    op.add_column('xbk_selections', sa.Column('grade', sa.String(length=20), nullable=True, comment='年级（高一/高二）'))
    op.create_index(op.f('ix_xbk_selections_grade'), 'xbk_selections', ['grade'], unique=False)
    op.add_column('xbk_students', sa.Column('grade', sa.String(length=20), nullable=True, comment='年级（高一/高二）'))
    op.create_index(op.f('ix_xbk_students_grade'), 'xbk_students', ['grade'], unique=False)
    op.drop_index(op.f('idx_znt_group_discussion_sessions_class_name'), table_name='znt_group_discussion_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_znt_group_discussion_sessions_class_name'), 'znt_group_discussion_sessions', ['class_name'], unique=False)
    op.drop_index(op.f('ix_xbk_students_grade'), table_name='xbk_students')
    op.drop_column('xbk_students', 'grade')
    op.drop_index(op.f('ix_xbk_selections_grade'), table_name='xbk_selections')
    op.drop_column('xbk_selections', 'grade')
    op.drop_index(op.f('ix_xbk_courses_grade'), table_name='xbk_courses')
    op.drop_column('xbk_courses', 'grade')
    op.create_index(op.f('idx_inf_typst_styles_sort'), 'inf_typst_styles', ['sort_order'], unique=False)
    op.create_index(op.f('idx_inf_typst_notes_published'), 'inf_typst_notes', ['published'], unique=False)
    op.create_index(op.f('idx_inf_typst_notes_compiled_hash'), 'inf_typst_notes', ['compiled_hash'], unique=False)
    op.create_index(op.f('idx_inf_typst_categories_sort'), 'inf_typst_categories', ['sort_order'], unique=False)
    op.create_index(op.f('idx_inf_typst_assets_sha256'), 'inf_typst_assets', ['sha256'], unique=False)
    op.create_index(op.f('idx_inf_typst_assets_note_id_path'), 'inf_typst_assets', ['note_id', 'path'], unique=False)
    # ### end Alembic commands ###
