"""add_owner_id_to_learning_content

Revision ID: fa302846ca5d
Revises: 20260509_lrn_chapters
Create Date: 2026-05-11 18:10:03.485757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa302846ca5d'
down_revision: Union[str, None] = '20260509_lrn_chapters'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_book_chapters_book_id'), table_name='ml_book_chapters')
    op.drop_index(op.f('ix_ml_book_chapters_slug'), table_name='ml_book_chapters')
    op.drop_index(op.f('ix_ml_books_module_key'), table_name='ml_books')
    op.add_column('sys_learning_content_items', sa.Column('owner_id', sa.Integer(), nullable=True, comment='所有者用户ID，NULL表示公共'))
    op.create_index(op.f('ix_sys_learning_content_items_owner_id'), 'sys_learning_content_items', ['owner_id'], unique=False)
    op.alter_column('xxjs_dianming', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_znt_conv_agent_type_created'), table_name='znt_conversations')
    op.drop_index(op.f('idx_znt_conv_session_created'), table_name='znt_conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_znt_conv_session_created'), 'znt_conversations', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_znt_conv_agent_type_created'), 'znt_conversations', ['agent_id', 'message_type', 'created_at'], unique=False)
    op.alter_column('xxjs_dianming', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_sys_learning_content_items_owner_id'), table_name='sys_learning_content_items')
    op.drop_column('sys_learning_content_items', 'owner_id')
    op.create_index(op.f('ix_ml_books_module_key'), 'ml_books', ['module_key'], unique=False)
    op.create_index(op.f('ix_ml_book_chapters_slug'), 'ml_book_chapters', ['book_id', 'slug'], unique=False)
    op.create_index(op.f('ix_ml_book_chapters_book_id'), 'ml_book_chapters', ['book_id'], unique=False)
    # ### end Alembic commands ###
