import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import type { ComponentProps } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { xbkDataApi } from "@services";
import type { XbkCourseSelectionWorkbookConfirmResponse, XbkCourseSelectionWorkbookConfirmStatus, XbkCourseSelectionWorkbookPreviewResponse } from "@services/xbk/data";
import { XbkCourseSelectionWorkbookModal } from "./XbkCourseSelectionWorkbookModal";

vi.mock("@services",()=>({xbkDataApi:{previewCourseSelectionWorkbook:vi.fn(),confirmCourseSelectionWorkbook:vi.fn()}}));
vi.mock("@/lib/toast",()=>({showMessage:{warning:vi.fn(),error:vi.fn(),success:vi.fn()}}));
type Props=ComponentProps<typeof XbkCourseSelectionWorkbookModal>;
const file=(name="选课表.xlsx")=>new File(["xlsx"],name,{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
const preview=(overrides:Partial<XbkCourseSelectionWorkbookPreviewResponse>={}):XbkCourseSelectionWorkbookPreviewResponse=>({plan_id:"p1",preview_token:"signed.token.value",token_version:1,expires_at:"2026-09-15T01:00:00+08:00",year:"2026-2027",term:"上学期",baseline_id:"b1",total_rows:54,changed:1,unchanged:53,changed_rows:[{sheet:"高一15班",row:8,grade:"高一",class_name:"15班",student_no:"S001",name:"张同学",baseline_course:"C01",submitted_course:"C02",target_course:"C02",action:"select"}],notice:"预览不预留名额；确认时重新校验。",...overrides});
const result=(overrides:Partial<XbkCourseSelectionWorkbookConfirmResponse>={}):XbkCourseSelectionWorkbookConfirmResponse=>({plan_id:"p1",status:"applied",changed:1,inserted:0,updated:1,...overrides});
const deferred=<T,>()=>{let resolve!:(x:T)=>void;const promise=new Promise<T>(r=>{resolve=r});return{promise,resolve}};
const setup=(filters:Props["filters"]={year:"2026-2027",term:"上学期"})=>{const props:Props={open:true,filters,onCancel:vi.fn(),onSuccess:vi.fn()};const view=render(<XbkCourseSelectionWorkbookModal {...props}/>);return{...view,props,update:(n:Partial<Props>)=>{Object.assign(props,n);view.rerender(<XbkCourseSelectionWorkbookModal {...props}/>);}}};
const choose=(f=file())=>fireEvent.change(screen.getByLabelText("学生选课工作簿"),{target:{files:[f]}});
const confirm=()=>screen.getByRole("button",{name:"确认应用"});

beforeEach(()=>{vi.resetAllMocks();vi.mocked(xbkDataApi.previewCourseSelectionWorkbook).mockResolvedValue(preview());vi.mocked(xbkDataApi.confirmCourseSelectionWorkbook).mockResolvedValue(result());});afterEach(cleanup);

describe("XBK R3 modal",()=>{
 it("runs preview then confirm with the same file and token",async()=>{const f=file(),v=setup();choose(f);expect(await screen.findByText("变更预览")).toBeInTheDocument();expect(screen.getByText("变更 1")).toBeInTheDocument();expect(screen.getByText("不变 53")).toBeInTheDocument();expect(screen.getByText("总计 54")).toBeInTheDocument();expect(screen.getByText("高一15班")).toBeInTheDocument();expect(screen.getByText("张同学")).toBeInTheDocument();expect(screen.getByText("C01")).toBeInTheDocument();expect(screen.getByText("C02")).toBeInTheDocument();expect(screen.getByText(/预览不预留名额/)).toBeInTheDocument();expect(xbkDataApi.previewCourseSelectionWorkbook).toHaveBeenCalledWith({file:f,year:"2026-2027",term:"上学期"});fireEvent.click(confirm());expect(await screen.findByText("选课变更已应用")).toBeInTheDocument();expect(xbkDataApi.confirmCourseSelectionWorkbook).toHaveBeenCalledWith({file:f,year:"2026-2027",term:"上学期",preview_token:"signed.token.value"});expect(v.props.onSuccess).toHaveBeenCalledOnce();});
 it.each([["already_applied","该工作簿已应用"],["no_changes","没有需要应用的变更"]])("shows %s",async(status,title)=>{vi.mocked(xbkDataApi.confirmCourseSelectionWorkbook).mockResolvedValue(result({status:status as XbkCourseSelectionWorkbookConfirmStatus,changed:0,updated:0}));setup();choose();await screen.findByText("变更预览");fireEvent.click(confirm());expect(await screen.findByText(title)).toBeInTheDocument();});
 it("validates filters and xlsx before preview",async()=>{setup({term:"上学期"});choose();expect(await screen.findByText("请先选择具体的学年和学期")).toBeInTheDocument();expect(xbkDataApi.previewCourseSelectionWorkbook).not.toHaveBeenCalled();cleanup();setup();choose(file("选课表.csv"));expect(await screen.findByText("学生选课工作簿仅支持 .xlsx 文件")).toBeInTheDocument();expect(xbkDataApi.previewCourseSelectionWorkbook).not.toHaveBeenCalled();});
 it("structures server errors",async()=>{vi.mocked(xbkDataApi.previewCourseSelectionWorkbook).mockRejectedValue({response:{data:{detail:{code:"XBK_WORKBOOK_CAPACITY_CONFLICT",message:"容量不足",issues:[{sheet:"高一15班",row:8,student_no:"S001",reason:"无剩余名额"}]}}}});setup();choose();expect(await screen.findByText("容量不足")).toBeInTheDocument();expect(screen.getByText(/XBK_WORKBOOK_CAPACITY_CONFLICT/)).toBeInTheDocument();expect(screen.getByText(/工作表 高一15班.*第 8 行.*无剩余名额/)).toBeInTheDocument();});
 it("locks duplicate confirm clicks",async()=>{const d=deferred<ReturnType<typeof result>>();vi.mocked(xbkDataApi.confirmCourseSelectionWorkbook).mockReturnValue(d.promise);setup();choose();await screen.findByText("变更预览");fireEvent.click(confirm());fireEvent.click(screen.getByRole("button",{name:"正在确认…"}));expect(xbkDataApi.confirmCourseSelectionWorkbook).toHaveBeenCalledTimes(1);await act(async()=>d.resolve(result()));});
 it("invalidates old token on file/filter changes and isolates closed generations",async()=>{const old=deferred<ReturnType<typeof preview>>();vi.mocked(xbkDataApi.previewCourseSelectionWorkbook).mockReturnValueOnce(old.promise).mockResolvedValueOnce(preview({changed:2,preview_token:"new.token"}));const v=setup();choose(file("旧.xlsx"));fireEvent.click(screen.getByRole("button",{name:"取消"}));v.update({open:false});v.update({open:true});choose(file("新.xlsx"));expect(await screen.findByText("变更 2")).toBeInTheDocument();await act(async()=>old.resolve(preview({changed:99})));expect(screen.queryByText("变更 99")).not.toBeInTheDocument();v.update({filters:{year:"2027-2028",term:"下学期"}});expect(screen.queryByText("变更预览")).not.toBeInTheDocument();expect(confirm()).toBeDisabled();});
});
