"""Opt-in PostgreSQL proof for the XBK active-selection unique migration.

The suite refuses non-loopback or non-test database URLs. Every test creates a
unique schema and removes it in ``finally``. It exercises the candidate Alembic
revision directly through Alembic's real PostgreSQL operations context.
"""
from __future__ import annotations

import importlib.util
import os
import re
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import create_async_engine

from app.services.xbk.selection_rules import (
    ACTIVE_SELECTION_UNIQUE_CONSTRAINT,
    is_active_selection_unique_violation,
)

if os.environ.get("XBK_ACTIVE_SELECTION_MIGRATION_PG") != "1":
    pytest.skip("requires dedicated PostgreSQL bootstrap", allow_module_level=True)

DATABASE_URL = os.environ.get("XBK_ACTIVE_SELECTION_MIGRATION_PG_URL", "").strip()
parsed = make_url(DATABASE_URL)
if (
    parsed.drivername != "postgresql+asyncpg"
    or parsed.host not in {"127.0.0.1", "localhost", "::1"}
    or not re.search(
        r"(?:^|[_-])(?:test|testing|ci)(?:$|[_-])", parsed.database or "", re.I
    )
):
    raise RuntimeError(
        "XBK migration PG tests require loopback asyncpg and a test-named database"
    )

_MIGRATION_PATH = (
    Path(__file__).parents[2]
    / "alembic/versions/20260914_0001_xbk_active_selection_unique.py"
)
_spec = importlib.util.spec_from_file_location("xbk_active_selection_migration", _MIGRATION_PATH)
assert _spec is not None and _spec.loader is not None
migration = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(migration)

_SCHEMA_PATTERN = re.compile(r"^xbk_r4_[0-9a-f]+$")
_OLD_UNIQUE = "uq_xbk_selections_year_term_student_no_course_code"


@asynccontextmanager
async def isolated_schema():
    schema = f"xbk_r4_{uuid.uuid4().hex}"
    assert _SCHEMA_PATTERN.fullmatch(schema)
    admin = create_async_engine(DATABASE_URL)
    engine = None
    try:
        async with admin.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))
        engine = create_async_engine(
            DATABASE_URL,
            connect_args={
                "server_settings": {
                    "search_path": schema,
                    "application_name": schema,
                    "statement_timeout": "10000",
                    "lock_timeout": "8000",
                }
            },
        )
        async with engine.begin() as conn:
            await conn.execute(
                text(
                    f"""
                    CREATE TABLE xbk_selections (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        year varchar(9) NOT NULL,
                        term varchar(20) NOT NULL,
                        grade varchar(20),
                        student_no varchar(50) NOT NULL,
                        name varchar(50),
                        course_code varchar(50) NOT NULL,
                        created_at timestamptz NOT NULL DEFAULT now(),
                        updated_at timestamptz NOT NULL DEFAULT now(),
                        is_deleted boolean NOT NULL DEFAULT false,
                        CONSTRAINT {_OLD_UNIQUE}
                            UNIQUE (year, term, student_no, course_code)
                    )
                    """
                )
            )
        yield engine, schema
    finally:
        if engine is not None:
            await engine.dispose()
        async with admin.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await admin.dispose()


async def run_revision(engine, direction: str) -> None:
    def invoke(sync_conn):
        context = MigrationContext.configure(sync_conn)
        with Operations.context(context):
            getattr(migration, direction)()

    async with engine.begin() as conn:
        await conn.run_sync(invoke)


async def index_exists(engine, name: str) -> bool:
    async with engine.connect() as conn:
        return bool(
            await conn.scalar(
                text(
                    "SELECT EXISTS ("
                    "SELECT 1 FROM pg_indexes "
                    "WHERE schemaname = current_schema() AND indexname = :name)"
                ),
                {"name": name},
            )
        )


async def insert_selection(
    engine,
    *,
    student_no: str,
    course_code: str,
    is_deleted: bool = False,
) -> None:
    async with engine.begin() as conn:
        await conn.execute(
            text(
                "INSERT INTO xbk_selections "
                "(year, term, student_no, course_code, is_deleted) "
                "VALUES ('2037-2038', '上学期', :student_no, :course_code, :deleted)"
            ),
            {
                "student_no": student_no,
                "course_code": course_code,
                "deleted": is_deleted,
            },
        )


def constraint_names(exc: BaseException) -> list[str]:
    names: list[str] = []
    current: BaseException | None = exc
    seen: set[int] = set()
    while current is not None and id(current) not in seen:
        seen.add(id(current))
        diag = getattr(current, "diag", None)
        name = getattr(diag, "constraint_name", None) or getattr(
            current, "constraint_name", None
        )
        if name:
            names.append(str(name))
        current = getattr(current, "orig", None) or getattr(current, "__cause__", None)
    return names


def test_upgrade_downgrade_upgrade_and_historical_duplicate_block():
    async def scenario():
        async with isolated_schema() as (engine, _schema):
            await run_revision(engine, "upgrade")
            assert await index_exists(engine, ACTIVE_SELECTION_UNIQUE_CONSTRAINT)

            await run_revision(engine, "downgrade")
            assert not await index_exists(engine, ACTIVE_SELECTION_UNIQUE_CONSTRAINT)

            await run_revision(engine, "upgrade")
            assert await index_exists(engine, ACTIVE_SELECTION_UNIQUE_CONSTRAINT)
            await run_revision(engine, "downgrade")

            await insert_selection(engine, student_no="DUP-1", course_code="C1")
            await insert_selection(engine, student_no="DUP-1", course_code="C2")
            with pytest.raises(RuntimeError, match="DUP-1=2"):
                await run_revision(engine, "upgrade")
            assert not await index_exists(engine, ACTIVE_SELECTION_UNIQUE_CONSTRAINT)

            async with engine.begin() as conn:
                await conn.execute(
                    text(
                        "UPDATE xbk_selections SET is_deleted = true "
                        "WHERE student_no = 'DUP-1' AND course_code = 'C2'"
                    )
                )
            await run_revision(engine, "upgrade")
            assert await index_exists(engine, ACTIVE_SELECTION_UNIQUE_CONSTRAINT)

    import asyncio

    asyncio.run(scenario())


def test_asyncpg_constraint_name_shape_and_application_classifier():
    async def scenario():
        async with isolated_schema() as (engine, _schema):
            await run_revision(engine, "upgrade")
            await insert_selection(engine, student_no="S1", course_code="C1")

            with pytest.raises(IntegrityError) as active_conflict:
                await insert_selection(engine, student_no="S1", course_code="C2")
            active_names = constraint_names(active_conflict.value)
            print(f"asyncpg active constraint chain: {active_names}")
            assert ACTIVE_SELECTION_UNIQUE_CONSTRAINT in active_names
            assert is_active_selection_unique_violation(active_conflict.value) is True

            await run_revision(engine, "downgrade")
            await insert_selection(engine, student_no="S2", course_code="C9")
            with pytest.raises(IntegrityError) as other_conflict:
                await insert_selection(engine, student_no="S2", course_code="C9")
            other_names = constraint_names(other_conflict.value)
            print(f"asyncpg non-target constraint chain: {other_names}")
            assert _OLD_UNIQUE in other_names
            assert ACTIVE_SELECTION_UNIQUE_CONSTRAINT not in other_names
            assert is_active_selection_unique_violation(other_conflict.value) is False

    import asyncio

    asyncio.run(scenario())
