import type React from "react";
import type { FlowBeautifyParams, FlowBeautifyResult } from "../../flow/beautify";
import type { FlowTidyResult } from "../../flow/tidy";
import type { RunnerState } from "../../hooks/useDapRunner";
import type { PythonLabFlowDiagnostic, PythonLabPseudocodeParseResponse } from "../../services/pythonlabDebugApi";
import type { PythonLabRuleSetV1 } from "../../pipeline/rules";

export type RightPanelProps = {
  generated: { python: string };
  code: string;
  setCode: (v: string) => void;
  codeMode: "auto" | "manual";
  setCodeMode: (v: "auto" | "manual") => void;
  revealLine: number | null;
  variableColumns: any;
  runner: RunnerState;
  runnerError: string | null;
  structuredEmphasisLog?: boolean;
  onToggleStructuredEmphasisLog?: (v: boolean) => void;
  flowDiagnostics?: PythonLabFlowDiagnostic[];
  flowExpandFunctions?: "all" | "top" | "none";
  setFlowExpandFunctions?: (v: "all" | "top" | "none") => void;
  onRun: () => void;
  onContinue: () => void;
  onPause: () => void;
  onStepOver: () => void;
  onStepInto: () => void;
  onStepOut: () => void;
  onReset: () => void;
  onToggleBreakpoint: (line: number) => void;
  onSetBreakpointEnabled: (line: number, enabled: boolean) => void;
  onSetBreakpointCondition: (line: number, condition: string) => void;
  onSetBreakpointHitCount: (line: number, hitCount: number | null) => void;
  onAddWatch: (expr: string) => void;
  onRemoveWatch: (expr: string) => void;
  onEvaluate: (expr: string) => Promise<{ ok: boolean; value?: string; type?: string; error?: string }>;
  onHistoryBack: () => void;
  onHistoryForward: () => void;
  onHistoryToLatest: () => void;
  onOpenTerminal: () => void;
  pipelineMode?: boolean;
  onTogglePipelineMode?: (v: boolean) => void;
  pseudocode?: PythonLabPseudocodeParseResponse | null;
  pseudocodeLoading?: boolean;
  pseudocodeError?: string | null;
  tidyResult?: FlowTidyResult | null;
  onApplyTidy?: () => void;
  beautifyParams?: FlowBeautifyParams;
  setBeautifyParams?: (next: FlowBeautifyParams) => void;
  beautifyResult?: FlowBeautifyResult | null;
  beautifyLoading?: boolean;
  beautifyError?: string | null;
  onRefreshBeautify?: () => void;
  onApplyBeautify?: (mode?: "nodes" | "nodes_edges") => void;
  canvasRoutingStyle?: "orthogonal" | "direct";
  setCanvasRoutingStyle?: (v: "orthogonal" | "direct") => void;
  ruleSet?: PythonLabRuleSetV1;
  setRuleSet?: (next: PythonLabRuleSetV1) => void;
  experimentId?: string;
};

export type ToolButtonStyle = React.CSSProperties;
