import type React from "react";
import type { FlowBeautifyResult } from "../../flow/beautify";
import type { RunnerState } from "../../hooks/useDapRunner";
import type { PythonLabFlowDiagnostic } from "../../services/pythonlabDebugApi";
import type { PyodideTerminalBridge } from "../../hooks/usePyodideRunner";
import type { DebugCapabilityMapV1 } from "../../adapters/debugCapabilityMap";

export type RightPanelProps = {
  generated: { python: string };
  code: string;
  setCode: (v: string) => void;
  codeMode: "auto" | "manual";
  setCodeMode: (v: "auto" | "manual") => void;
  revealLine: number | null;
  variableColumns: any;
  runner: RunnerState;
  debugCapabilities?: DebugCapabilityMapV1;
  runnerError: string | null;
  lastLaunchMode?: "idle" | "run" | "debug";
  terminalBridge?: PyodideTerminalBridge | null;
  flowDiagnostics?: PythonLabFlowDiagnostic[];
  flowExpandFunctions?: "all" | "top" | "none";
  setFlowExpandFunctions?: (v: "all" | "top" | "none") => void;
  onRebuildFlowFromCode?: () => void | Promise<void>;
  onRun: (stdinLines?: string[]) => void;
  onDebug: () => void;
  onTerminalInput: (text: string) => void;
  onContinue: () => void;
  onPause: () => void;
  onStepOver: () => void;
  onStepInto: () => void;
  onStepOut: () => void;
  onReset: () => void;
  onToggleBreakpoint: (line: number) => void;
  onSetBreakpointEnabled: (line: number, enabled: boolean) => void;
  onSetBreakpointCondition: (line: number, condition: string) => void;
  onSetBreakpointHitCount: (line: number, hitCount: number | null) => void;
  onAddWatch: (expr: string) => void;
  onRemoveWatch: (expr: string) => void;
  onEvaluate: (expr: string) => Promise<{ ok: boolean; value?: string; type?: string; error?: string }>;
  onHistoryBack: () => void;
  onHistoryForward: () => void;
  onHistoryToLatest: () => void;
  beautifyResult?: FlowBeautifyResult | null;
  beautifyLoading?: boolean;
  beautifyError?: string | null;
  onRefreshBeautify?: () => void;
  onClearPendingOutput?: () => void;
};

export type ToolButtonStyle = React.CSSProperties;
